#!/bin/sh

echo
echo "*************************************************"
echo "* This server is configured using Ansible.      *"
echo "*                                               *"
echo "* For more information:                         *"
echo "* https://github.com/TizianoPerrucci/prudentia  *"
echo "*************************************************"
echo