sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install codecov
install:
  - "pip install -r requirements-dev.txt"
script:
  - "./test.sh"
after_success:
  - codecov
notifications:
  slack: ssq:3XEKmie5OvsOo4PDvOyMU1nb
