sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install codecov
install:
  - "pip install -r requirements-dev.txt"
script:
  - "./test.sh"
after_success:
  - codecov
notifications:
  slack: ssq:3XEKmie5OvsOo4PDvOyMU1nb
