sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - pip install codecov
install:
  - "pip install -r requirements.txt"
script:
  - "./test.sh"
after_success:
  - codecov
notifications:
  slack: ssq:3XEKmie5OvsOo4PDvOyMU1nb
