---
  # this tell ucf to keep existing grub configuration and don't update
  - name: Common setup | Preventing ucf to ask information
    action: copy src=$root/files/common/ucf.conf dest=/etc/ucf.conf mode=644 backup=yes
    only_if: "not $testing"

  - name: Common setup | Upgrade distribution
    action: shell apt-get update && apt-get upgrade -y
    only_if: "not $testing"

  - name: Common setup | Message of the day explaining server is under Ansible control
    action: copy src=$root/files/common/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755

  - name: Common setup | Authorize keys
    authorized_key: user=$user key='$FILE($item)'
    with_items:
      - $root/files/common/tiziano_hubskip-ws.pub
      - $root/files/common/tiziano_ubuntu-air.pub
      - $root/files/common/tiziano_mac-air.pub
      - $root/files/common/jurg.pub
      - $root/files/common/jasper.pub
    only_if: "not $testing"

  - name: Common setup | Install common apt packages
    action: apt pkg=$item update-cache=yes state=present
    with_items:
      - python-software-properties
      - reptyr
      - htop