---
  # Parameters:
  #  $prudentia_dir
  
  # this tell ucf to keep existing grub configuration and don't update
  - name: Common setup | Preventing ucf to ask information
    action: copy src=$prudentia_dir/files/common/ucf.conf dest=/etc/ucf.conf mode=644 backup=yes
    only_if: "not $testing"
    sudo: yes
    tags: common

  - name: Common setup | Upgrade distribution
    action: shell apt-get update && apt-get upgrade -y
    only_if: "not $testing"
    sudo: yes
    tags: common

  - name: Common setup | Message of the day explaining server is under Ansible control
    action: copy src=$prudentia_dir/files/common/etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
    sudo: yes
    tags: common

  - name: Common setup | Install common apt packages
    action: apt pkg=$item update-cache=yes state=present
    with_items:
      - python-software-properties
      - reptyr
      - htop
      - curl
      - build-essential
    sudo: yes
    tags: common

#  - name: Common setup | Authorize keys
#    authorized_key: user=$user key='$FILE($item)'
#    with_items:
#      - $prudentia_dir/files/common/tiziano_mac-air.pub
#    only_if: "not $testing"
#    tags: common