---
  # Parameters:
  #  $root_dir
  #  $ssh_dir
  
  - include: $root_dir/tasks/git.yml

    # If known_hosts does not exists, make sure to use the ssh_key task
  - name: GitHub | Read known_hosts content
    action: shell [ -f $ssh_dir/.ssh/known_hosts ] && [ -n "$(grep github $ssh_dir/.ssh/known_hosts)" ] && echo 'found!' || echo ''
    register: github_known
    tags: github

  - name: GitHub | Add github.com to known_hosts
    action: shell ssh-keyscan github.com >> $ssh_dir/.ssh/known_hosts
    only_if: " '${github_known.stdout}' == '' "
    tags: github