---
  # Parameters:
  #  $prudentia_dir

  - name: Java 7 | Check if is present
    command: test -x /usr/bin/java
    ignore_errors: yes
    register: java_present
    tags: java

  - name: Java 7 | Add apt repository
#    action: apt_repository repo=ppa:webupd8team/java
#
# OTN license must be acknoweldged and the installer does not use the correct cookie so folling this post
# source http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html
# I found out a guy that maintains a temporary ppa to overcome the issue
    action: apt_repository repo=ppa:feniix/java
    when: java_present|failed
    tags: java
    sudo: yes

  - name: Java 7 | Accept the Oracle license before the installation
    action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    when: java_present|failed
    tags: java
    sudo: yes

  - name: Java 7 | Install
    action: apt update-cache=yes force=yes state=present pkg=oracle-java7-installer
    when: java_present|failed
    tags: java
    sudo: yes