---
  # Parameters:
  #  prudentia_dir

  - include: "{{prudentia_dir}}/tasks/java7.yml"

  - name: Jenkins | Add GPG key to apt keyring
    action: shell wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
    tags: jenkins
    sudo: yes

  - name: Jenkins | Add apt repository
    action: copy src={{prudentia_dir}}/files/jenkins/apt-source dest=/etc/apt/sources.list.d/jenkins.list mode=644
    tags: jenkins
    sudo: yes

  - name: Jenkins | Install
    action: apt update-cache=yes force=yes state=present pkg=jenkins
    tags: jenkins
    register: jenkins_installed
    sudo: yes

  - name: Jenkins | Wait for start
    wait_for: port=8080 delay=30
    when: jenkins_installed.changed
    tags: jenkins