---
  # Parameters:
  #  prudentia_dir
  #  mysql_root_password

  - name: MySQL | Check if installed
    command: test -x /usr/bin/mysql
    register: mysql_present
    ignore_errors: yes
    tags: mysql

  - name: MySQL | Preset root password
    shell: echo mysql-server-5.5 mysql-server/{{item}} password {{mysql_root_password}} | debconf-set-selections
    with_items:
      - root_password
      - root_password_again
    when: mysql_present|failed
    tags: mysql
    sudo: yes

  - name: MySQL | Install MySQL server
    apt: update-cache=yes force=yes state=present pkg=mysql-server
    when: mysql_present|failed
    tags: mysql
    sudo: yes

  - name: MySQL | Copy configuration file
    copy: src={{prudentia_dir}}/files/mysql/my.cnf dest=/etc/mysql/my.cnf backup=yes
    register: mysql_conf
    tags: mysql
    sudo: yes

  - name: MySQL | Restart
    service: name=mysql state=restarted
    when: mysql_conf.changed
    tags: mysql
    sudo: yes