---
  # Parameters:
  #  $mysql_root_password
  #  $prudentia_dir

  - name: MySQL | Check if installed
    action: test -x /usr/bin/mysql
    register: mysql_present
    tags: mysql

  - name: MySQL | Preset root password
    action: shell echo mysql-server-5.5 mysql-server/$item password {{mysql_root_password}} | debconf-set-selections
    with_items:
      - root_password
      - root_password_again
    when: mysql_present|failed
    tags: mysql
    sudo: yes

  - name: MySQL | Install MySQL server
    action: apt update-cache=yes force=yes state=present pkg=mysql-server
    when: mysql_present|failed
    tags: mysql
    sudo: yes

  - name: MySQL | Copy configuration file
    action: copy src=$prudentia_dir/files/mysql/my.cnf dest=/etc/mysql/my.cnf backup=yes
    register: mysql_conf
    tags: mysql
    sudo: yes

  - name: MySQL | Restart
    action: service name=mysql state=restarted
    when: mysql_conf.changed
    tags: mysql
    sudo: yes