---
  # Parameters:
  #  prudentia_dir

  - name: PostgreSQL | Check if is installed
    command: test -x /usr/bin/psql
    register: psql_present
    ignore_errors: yes
    tags: psql

  - name: PostgreSQL | Install
    apt: update-cache=yes force=yes state=present pkg={{item}}
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    sudo: yes
    when: psql_present|failed
    tags: psql
