---
  # Parameters:
  #  prudentia_dir

  - include: "{{prudentia_dir}}/tasks/chrome.yml"

  # selenium needs java
  - include: "{{prudentia_dir}}/tasks/java7.yml"

  - name: Xvfb | Install
    apt: force=yes state=present pkg=xvfb
    sudo: yes
    tags: protractor

  - name: Protractor | Check if is present
    command: test -x /usr/bin/webdriver-manager
    ignore_errors: yes
    register: protractor_present
    tags: protractor

  - name: Protractor and Webdriver | Install
    command: "{{item}}"
    with_items:
      - npm install -g protractor
      - webdriver-manager update
    sudo: yes
    when: protractor_present|failed
    tags: protractor

  - name: Webdriver daemon | Copy upstart script
    action: template src={{prudentia_dir}}/files/protractor/webdriver-upstart.conf dest=/etc/init/webdriver.conf
    sudo: yes
    tags: protractor
