---
  # Parameters:
  #  $prudentia_dir
  #  $remote_prudentia_install_dir
  #  $remote_prudentia_version

  - include: $prudentia_dir/tasks/python.yml

  - name: Prudentia | Install Virtualenv
    pip: name=virtualenv
    sudo: yes
    tags: prudentia

  - name: Prudentia | Checkout git repository
    git: repo=$prudentia_git_repository dest=$remote_prudentia_install_dir version=$remote_prudentia_version
    tags:
      - prudentia
      - update

  - name: Prudentia | Setup
    command: $remote_prudentia_install_dir/./prudentia.sh setup
    tags:
      - prudentia
      - update
