---
  - name: Python | Install
    apt: update-cache=yes pkg={{item}} state=present
    when: ansible_os_family == "Debian"
    tags: python
    sudo: yes
    with_items:
      - python
      - python-dev
      - python-pip

#  - name: Python | Distribute setup
#    shell: curl -O http://python-distribute.org/distribute_setup.py && /usr/bin/python2.7 distribute_setup.py
#    when: ansible_os_family == "Debian"
#    sudo: yes
#    tags: python