---
  # Parameters:
  #  $prudentia_dir

  - name: Ruby | Check if RVM is present
    command: test -x /home/$ansible_user_id/.rvm/scripts/rvm
    ignore_errors: yes
    register: rvm_present
    tags: ruby

  - name: Ruby | Install last stable
    shell: curl -L https://get.rvm.io | bash -s stable --ruby
    when: rvm_present|failed
    tags: ruby

  # we use bash -l because we need to get ruby and gems in PATH
  - name: Ruby | Install bundler
    shell: /bin/bash -lc 'gem install bundler'
    tags: ruby
