---
  - include: $root/tasks/mysql_5.5.yml

  - name: Database | Create directory
    action: file dest=$install_dir owner=root group=root mode=755 state=directory
    tags: update

  - name: Database | Copy run script
    action: copy src=$root/components/database/files/run.sh dest=$install_dir/run.sh mode=744
    tags: update

  - name: Database | Copy SQL files
    action: copy src=$root/components/database/files/$item dest=$install_dir/$item
    with_items:
      -
    tags: update

  - name: Database | Run SQL files
    action: command ./run.sh $database_user $database_pwd $database_host chdir=$install_dir
    tags: update

  - name: Database | Copy dump
    action: copy src=$root/components/database/files/$database_dump_file dest=$install_dir/$database_dump_file
    register: database_copy_dump
    when_unset: $no_dump

  - name: Database | Import dump
    action: shell zcat flights.dump.gz | mysql --user=$database_user --password=$database_pwd --host=$database_host $database_name chdir=$install_dir
    when_changed: $database_copy_dump
    when_unset: $no_dump