---
  # Parameters:
  #  prudentia_dir (provided)

  # This forces ucf to keep existing grub configuration and don't update it.
  - name: Common setup | Preventing ucf to ask information
    copy: src={{prudentia_dir}}/files/common/ucf.conf dest=/etc/ucf.conf mode=644 backup=yes
    when: ansible_system == "Linux" and not testing
    sudo: yes
    tags: common

  - name: Common setup | Message of the day explaining server is under Prudentia control
    copy: src={{prudentia_dir}}/files/common/etc-update-motd-d-95-prudentia dest=/etc/update-motd.d/95-prudentia mode=755
    when: ansible_system == "Linux"
    sudo: yes
    tags: common

  - name: Common setup | Install common apt packages
    apt: update-cache=yes pkg={{item}} state=present
    when: ansible_os_family == "Debian"
    with_items:
      - build-essential
      - reptyr
      - htop
      - curl
      - python-software-properties
      - python-httplib2
    sudo: yes
    tags: common
