---
   # Provided:
    # java_jre_version: JRE version
    # java_jre_build: JRE build number
    # You may find it here
    #   - http://www.oracle.com/technetwork/java/javase/downloads/server-jre7-downloads-1931105.html
    # or here
    #   - http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html

  - name: JRE headless | Are we running on x64?
    set_fact:
      platform: "x64"
    when: ansible_architecture == "x86_64" and ansible_os_family == "Debian"
    tags:
      - jre-headless

  - name: JRE headless | Fail if it isn't x64
    fail: msg="Unknown platform architecture (should be x64, got {{ansible_architecture}}"
    when: platform != "x64" and ansible_os_family == "Debian"
    tags:
      - jre-headless

  - name: JRE headless | Set JRE download URL
    set_fact:
      jre_download_url: "http://download.oracle.com/otn-pub/java/jdk/{{java_jre_version}}-{{java_jre_build}}/server-jre-{{java_jre_version}}-linux-{{platform}}.tar.gz"
    when: ansible_os_family == "Debian"
    tags:
      - jre-headless

  - name: JRE headless | Get jdk directory name
    shell: "echo jdk1.{{java_jre_version}} |sed 's/u/.0_/'"
    register: jdk_dir
    when: ansible_os_family == "Debian"
    sudo: yes
    tags:
      - jre-headless

  - name: JRE headless | Download and install
    shell: "{{item}}"
    with_items:
      - "mkdir -p /usr/lib/jvm"
      - "wget -O /usr/lib/jvm/{{jdk_dir.stdout}}.tgz --no-check-certificate --no-cookies --header \"Cookie: oraclelicense=accept-securebackup-cookie\" {{jre_download_url}}"
      - "cd /usr/lib/jvm && tar -zxf {{jdk_dir.stdout}}.tgz"
      - "rm -f /usr/lib/jvm/{{jdk_dir.stdout}}.tgz"
    when: ansible_os_family == "Debian"
    sudo: yes
    tags:
      - jre-headless

  - name: JRE headless | Print postinstall help
    shell: "{{item}}"
    with_items:
      - "update-alternatives --remove-all javac"
      - "update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/{{jdk_dir.stdout}}/bin/javac 1"
      - "update-alternatives --remove-all java"
      - "update-alternatives --install /usr/bin/java java /usr/lib/jvm/{{jdk_dir.stdout}}/bin/java 1"
      - "update-alternatives --set javac /usr/lib/jvm/{{jdk_dir.stdout}}/bin/javac"
      - "update-alternatives --set java /usr/lib/jvm/{{jdk_dir.stdout}}/bin/java"
    when: ansible_os_family == "Debian"
    sudo: yes
    tags:
      - jre-headless
