---
  # Parameters:
  #  prudentia_dir (provided)

  - include: "{{prudentia_dir}}/tasks/java.yml"
    tags:
      - jenkins

  - name: Jenkins | Add GPG key to apt keyring
    shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
    when: ansible_os_family == "Debian"
    tags:
      - jenkins
    become: yes

  - name: Jenkins | Add apt repository
    copy: src={{prudentia_dir}}/files/jenkins/apt-source dest=/etc/apt/sources.list.d/jenkins.list mode=644
    when: ansible_os_family == "Debian"
    tags:
      - jenkins
    become: yes

  - name: Jenkins | Install
    apt: update-cache=yes force=yes state=present pkg=jenkins
    when: ansible_os_family == "Debian"
    tags:
      - jenkins
    register: jenkins_installed
    become: yes

  - name: Jenkins | Wait for start
    wait_for: port=8080 delay=30
    when: jenkins_installed.changed
    tags:
      - jenkins
