---
  # Parameters:
  #  monit_repo
  #  monit_package

  - name: Monit | Check if is installed
    command: dpkg-query -W monit
    when: ansible_os_family == "Debian"
    register: monit_check_deb
    failed_when: monit_check_deb.rc > 1
    changed_when: monit_check_deb.rc == 1
    tags: monit

  - name: Monit | Download
    get_url: url="{{monit_repo}}/{{monit_package}}" dest="/tmp/{{monit_package}}"
    when: monit_check_deb.rc == 1
    tags: monit

  - name: Monit | Install
    apt: deb="/tmp/{{monit_package}}"
    when: monit_check_deb.rc == 1
    sudo: yes
    tags: monit
