---
  # Parameters:
  #  prudentia_dir (provided)
  #  mysql_root_password

  - name: MySQL | Check if is installed
    command: test -x /usr/bin/mysql
    when: ansible_system == "Linux"
    register: mysql_present
    ignore_errors: yes
    tags:
      -  mysql

  - name: MySQL | Preset root password
    shell: echo mysql-server-5.5 mysql-server/{{item}} password {{mysql_root_password}} | debconf-set-selections
    when: ansible_os_family == "Debian" and mysql_present|failed
    with_items:
      - root_password
      - root_password_again
    tags:
      -  mysql
    become: yes

  - name: MySQL | Install
    apt: force=yes state=present pkg=mysql-server
    when: ansible_os_family == "Debian" and mysql_present|failed
    tags:
      -  mysql
    become: yes

  - name: MySQL | Get MySQL version
    command: mysql --version
    register: mysql_version
    tags:
      - mysql

  - name: MySQL | Parse version
    set_fact:
      mysql_version: "{{ mysql_version.stdout | regex_replace('^.*Distrib (\\d+(.\\d+)*),.*$', '\\1') }}"

  - name: MySQL | Copy 5.5 configuration file
    copy: src={{prudentia_dir}}/files/mysql/my.cnf dest=/etc/mysql/my.cnf backup=yes
    when: ansible_os_family == "Debian" and mysql_version|version_compare('5.7', '<')
    register: mysql_conf
    tags:
      -  mysql
    become: yes

  - name: MySQL | Copy 5.7 configuration file
    copy: src={{prudentia_dir}}/files/mysql_5.7/my.cnf dest=/etc/mysql/my.cnf backup=yes
    when: ansible_os_family == "Debian" and mysql_version|version_compare('5.7', '>=')
    register: mysql_conf
    tags:
      -  mysql
    become: yes

  - name: MySQL | Restart
    service: name=mysql state=restarted
    when: mysql_conf.changed
    tags:
      -  mysql
    become: yes
