---
  # Parameters:
  #  prudentia_dir (provided)

  - include: "{{prudentia_dir}}/tasks/chrome.yml"
    tags:
      - protractor

  # selenium needs java
  - include: "{{prudentia_dir}}/tasks/java.yml"
    tags:
      - protractor

  - include: "{{prudentia_dir}}/tasks/nodejs.yml"
    tags:
      - protractor

  - name: Xvfb | Install
    apt: force=yes state=present pkg=xvfb
    when: ansible_distribution == "Ubuntu"
    become: yes
    tags:
      - protractor

  - name: Protractor | Check if is present
    command: test -x /usr/local/bin/webdriver-manager
    when: ansible_system == "Linux"
    ignore_errors: yes
    register: protractor_present
    tags:
      - protractor

  - name: Protractor and Webdriver | Install
    command: "{{item}}"
    with_items:
      - "npm install -g protractor"
      - "webdriver-manager update"
    become: yes
    when: ansible_system == "Linux" and protractor_present|failed
    tags:
      - protractor

  - name: Webdriver daemon | Copy upstart script
    template: src={{prudentia_dir}}/files/protractor/webdriver-upstart.conf dest=/etc/init/webdriver.conf
    when: ansible_distribution == "Ubuntu"
    become: yes
    tags:
      - protractor

  - name: Webdriver daemon | Start
    service: name=webdriver state=started
    when: ansible_distribution == "Ubuntu"
    become: yes
    tags:
      - protractor
