---
  # Parameters:
  #  prudentia_dir (provided)

  - include: "{{prudentia_dir}}/tasks/java.yml"
    tags: tomcat

  - name: Tomcat | Install
    apt: update-cache=yes force=yes state=present pkg=tomcat7
    sudo: yes
    tags: tomcat

  - name: Tomcat | Install APR native library
    apt: update-cache=yes force=yes state=present pkg=libtcnative-1
    sudo: yes
    tags: tomcat
