---
  # Parameters:
  #  prudentia_dir (provided)

  - include: "{{prudentia_dir}}/tasks/java.yml"
    tags:
      - tomcat

  - name: Tomcat | Install
    apt: force=yes state=present pkg=tomcat7
    become: yes
    tags:
      - tomcat

  - name: Tomcat | Install APR native library
    apt: force=yes state=present pkg=libtcnative-1
    become: yes
    tags:
      - tomcat
